version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app-1:
    build:
      context: .
    image: ikhtiyor31/node-app
    platform: linux/amd64
    environment:
      - PORT=3000
