version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app-1:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
  node-app-2:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
